 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - pwd
     - mkdir lib
     - cd lib
     - git clone https://github.com/BareConductive/mpr121
     - cd ..
     - pip lib update

 script:
     - platformio run
